### ISSUE TITLE
Recv throwing error when getting requests and saying (resource is unavailable)

### ISSUE THREAD

**Issue by Taanviir** [samih713/webserv#56]

**Comment by samih713** [comment]
The issue arose because the recv function returned -1 when there was no data to be read (it returns 0 when the client closes the connection). The -1 return value caused an exception to be thrown, which was caught and led to the client's connection being closed in the catch block. However, the client expects the connection to remain open (to send the next request, such as for a CSS file). As a result, the connection was prematurely closed, preventing the client from sending the subsequent request.
